### ISSUE TITLE
Very slow startup on tdcli

### ISSUE THREAD

**Issue by punassuming** [handyman5/poodledo#2]
Whenever, I launch tdcli, I am getting extremely slow startups, on the order of 30 seconds, even after I have authenticated completely.  I am not sure what is causing the delay, but I have tried looking at python -v tdcli it it holds for most of the time after showing import StringIO.

When I import StringIO, or any of the other import commands I see when viewing the verbose log, I have no delay.

**Comment by handyman5** [comment]
It's not actually StringIO's fault; the delay comes from assembling the lexer that parses the task string. Plex (the lexer library I'm using) only causes a delay of a couple of seconds on my machine, but I can see where it would take a lot longer under other conditions.

I'll look into replacing plex with the built-in re.Scanner tool: http://www.evanfosmark.com/2009/02/sexy-lexing-with-python/. Thanks for the bug report!

**Comment by handyman5** [comment]
I've added a cache of the lexer object, so that once it's been generated it will be re-used between runs. It significanty improves performance on my machine. Can you please check it out and see if it helps on your end?

**Comment by punassuming** [comment]
Adam,

That seemed to really pick things up.  One other problem I am having
is the need to add an app_id and app_token myself  to the AppClient
class whenever I update the repo.  Is there any way to add that stuff
into the rc file to prevent this?

Thanks,

Rich

On Fri, Nov 11, 2011 at 11:56 AM, Adam Compton
reply@reply.github.com
wrote:

> I've added a cache of the lexer object, so that once it's been generated it will be re-used between runs. It significanty improves performance on my machine. Can you please check it out and see if it helps on your end?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/handyman5/poodledo/issues/2#issuecomment-2710324

## 

Rich

**Comment by handyman5** [comment]
Great idea! I've added that to the latest commit. Please try it out and let me know what you think.

Thanks,
Adam

**Comment by handyman5** [comment]
The current code doesn't use the lexer (or its cache) anymore, and the other issue was addressed a year ago. Closing this ticket.
