### ISSUE TITLE
Make Poodledo a Package

### ISSUE THREAD

**Issue by johncronin3** [handyman5/poodledo#4]
I'd like to include this as a submodule in another Github project.  I'd like to include it as a package.  It will need the **init**.py file created.

http://docs.python.org/tutorial/modules.html

**Comment by handyman5** [comment]
Hi John,

I've added an **init**.py; can you please let me know if this addressed your use case?

Thanks,
Adam

**Comment by johncronin3** [comment]
It worked.  Thanks

On Wed, Jun 27, 2012 at 1:28 AM, Adam Compton <
reply@reply.github.com

**Comment by handyman5** [comment]
Awesome; thanks for the suggestion!
